site_name: HYX's Bioinformatics 
site_description: '多组学联合分析'
site_author: 'xanadu314'
site_url: 'https://xanadu314.github.io/pathongs/'
theme:
  name: 'material'
  palette:
    scheme: default
    primary: 'indigo'
  features:
    - navigation.tabs
    - navigation.sections
  #custom_dir: sources
copyright: 'Copyright &copy; 2016 - 2021 HZCDC@Lab'
repo_url: https://github.com/indexofire/pathongs/

extra:
  palette:
    primary: 'blue'

extra_css:
  - assets/stylesheets/extra.css

nav:
  - '首页': index.md
  - '数据分析笔记':
    - '第零章 开始之前': book/main.md
    - '第一章 常用工具':
      - '01. 基因组公共数据库': book/C01_Common-Utility/01_database.md
      - '02. 下载基因组数据': book/C01_Common-Utility/02_get-data.md
      - '03. Entrez 工具': book/C01_Common-Utility/03_entrez.md
      - '04. EMBOSS 工具集': book/C01_Common-Utility/04_emboss.md
      - '05. Blast 比对': book/C01_Common-Utility/05_blast.md
      - '06. FastQC': book/C01_Common-Utility/06_fastqc.md
      - '07. Multiqc': book/C01_Common-Utility/07_multiqc.md
      - '08. SeqKit 工具': book/C01_Common-Utility/08_seqkit.md
      - '09. Kmer 工具': book/C01_Common-Utility/09_kmer.md
    - '第二章 组装与比对':
      - '01. 基本比对流程': book/C02_Raw-Data-to-Genome/01_bwa-samtools-pipeline.md
      - '02. Quast 验证': book/C02_Raw-Data-to-Genome/02_quast.md
      - '03. 细菌基因组组装': book/C02_Raw-Data-to-Genome/03_bacteria-assembly.md
      - '04. 病毒基因组组装': book/C02_Raw-Data-to-Genome/04_virus-assembly.md
      - '05. GATK3': book/C02_Raw-Data-to-Genome/05_gatk3.md
      - '06. GATK4': book/C02_Raw-Data-to-Genome/06_gatk4.md
      #- '10. snap': C04_Pathogen-Genome-Assembly/10_snap.md
      - '11. 长序列比对': book/C02_Raw-Data-to-Genome/11_long-noisy-reads-assembly.md
      - '12. 二代三代混合组装': book/C02_Raw-Data-to-Genome/12_hybrid-assembly.md
      - '14. bwa 长序列比对': book/C02_Raw-Data-to-Genome/14_bwa-long-sequence-mapping.md
      #- '15. whatshap': C04_Pathogen-Genome-Assembly/15_whatshap.md
    - '第三章 基因组注释':
      - '01. Prokka 快速注释': book/C03_Genome-Annotation/01_prokka.md
      - '02. 在线注释工具 rast': book/C03_Genome-Annotation/02_rast.md
      - '03. 注释工具 PGAAP': book/C03_Genome-Annotation/03_pgaap.md
      - '04. SNP注释工具 snpEFF': book/C03_Genome-Annotation/04_snpeff.md
      - '05. COG注释': book/C03_Genome-Annotation/05_cog.md
    - '第四章 基因组比较':
      - '01. mummer': book/C06_Genome-Compare/01_mummer.md
      - '02. nucdiff': book/C06_Genome-Compare/02_nucdiff.md
      - '03. mauve': book/C06_Genome-Compare/03_mauve.md
      - '04. sibelia': book/C06_Genome-Compare/04_sibelia.md
      - '05. ani': book/C06_Genome-Compare/05_ani.md
      - '10. bigsi': book/C06_Genome-Compare/10_bigsi.md
    - '第五章 泛基因组分析':
      - '01. Pangenome 概述': book/C07_PanGenome-and-CoreGenome/01_pangenome.md
      - '02. Get_Homologues 分析': book/C07_PanGenome-and-CoreGenome/02_get_homologues.md
      - '03. BPGA 分析': book/C07_PanGenome-and-CoreGenome/03_bpga.md
      - '04. Roary 分析': book/C07_PanGenome-and-CoreGenome/04_roary.md
      - '05. panseq 分析': book/C07_PanGenome-and-CoreGenome/05_panseq.md
      - '07. OrthMCL 分析': book/C07_PanGenome-and-CoreGenome/07_orthmcl.md
      - '08. ITEP 分析': book/C07_PanGenome-and-CoreGenome/08_itep.md
    - '第六章 基因组可视化':
      - '01. igv 查看比对结果': book/C08_Genome-Visualization/01_igv.md
      - '02. BRIG 分析工具': book/C08_Genome-Visualization/02_brig.md
      - '03. circos 工具使用': book/C08_Genome-Visualization/03_circos.md
    - '第七章 综合分析平台':
      - '01. 基于 docker 镜像': book/C09_Analysis-Platform/01_docker.md
      - '02. Galaxy 平台': book/C09_Analysis-Platform/02_galaxy.md
      - '03. Amazon EC2 云平台': book/C09_Analysis-Platform/03_amazon.md
      - '04. 其他平台': book/C09_Analysis-Platform/04_others.md
      - '05. anvio': book/C16_Standalone-Platform/01_anvio.md
      - '02. galaxy': book/C16_Standalone-Platform/02_galaxy.md
    - '第八章 重组与种群分析':
      - '01. 病毒重组': book/C10_Recombination-and-Population-Structure/01_virus-recombination.md
      - '02. Gubbins 分析': book/C10_Recombination-and-Population-Structure/02_gubbins.md
      - '03. BAPS': book/C10_Recombination-and-Population-Structure/03_baps.md
    - '第九章 细菌扫描工具':
      - '01. SRST2 短序列扫描工具': book/C11_Insilico-Scanning/01_srst2.md
      - '02. MLST 扫描工具': book/C11_Insilico-Scanning/02_mlst.md
      - '03. Ariba 耐药基因': book/C11_Insilico-Scanning/03_ariba.md
      - '04. Abricate 多功能扫描工具': book/C11_Insilico-Scanning/04_abricate.md
    - '第十章 宏基因组分析':
      - '01. kraken': book/C12_Metagenomics-Analysis/01_kraken.md
      - '02. centrifuge': book/C12_Metagenomics-Analysis/02_centrifuge.md
      - '03. bracken': book/C12_Metagenomics-Analysis/03_bracken.md
      - '04. sourmash': book/C12_Metagenomics-Analysis/04_sourmash.md
      - '05. clark': book/C12_Metagenomics-Analysis/05_clark.md
      - '06. krona': book/C12_Metagenomics-Analysis/06_krona.md
      - '07. pavian': book/C12_Metagenomics-Analysis/07_pavian.md
      - '08. supri': book/C12_Metagenomics-Analysis/08_supri.md
      - '09. shotgun 分析': book/C12_Metagenomics-Analysis/09_shotgun.md
      - '10. 16S 种群分析': book/C12_Metagenomics-Analysis/10_16s.md
      - '11. KmerFinder': book/C12_Metagenomics-Analysis/11_kmerfinder.md
      - '12. Meta-BEETL': book/C12_Metagenomics-Analysis/12_meta-beetl.md
    - '第十一章 单分子测序':
      - '01. nanopore': book/C13_Single-Molecular-Sequencing/01_nanopore.md
      - '02. pacbio': book/C13_Single-Molecular-Sequencing/02_pacbio.md
      - '03. canu': book/C13_Single-Molecular-Sequencing/03_canu.md
      - '04. trimming': book/C13_Single-Molecular-Sequencing/04_seqs-polish.md
      - '06. hybrid': book/C13_Single-Molecular-Sequencing/06_hybrid-assembling.md
    - '第十二章 多重序列比对':
      - '01. 多重序列比对': book/C14_Multiple-Sequence-Alignment/01_msa.md
    - '第十三章 进化树构建分析':
      - '00. 构建进化书': book/C15_Phylogeny-Analysis/00_all-about-phylogeny.md
      - '01. RAxML': book/C15_Phylogeny-Analysis/02_raxml.md
      - '02. figtree': book/C15_Phylogeny-Analysis/01_figtree.md
      - '03. ggtree': book/C15_Phylogeny-Analysis/02_ggtree.md
    - '第十七章 分子地理流行病学':
      - '04. CartoDB': book/C17_Pathogen-Geospatial-Analysis/04_cartodb.md
      - '05. leaflet': book/C17_Pathogen-Geospatial-Analysis/05_leaflet.md
    - '第十八章 分析实践':
      - '01. 细菌SNP溯源分析一': book/C18_Analysis-Examples/01_trace-Pae-from-different-source-by-SNP.md
      - '02. 细菌比较基因组学研究': book/C18_Analysis-Examples/02_comparative-analysis-Ban-genomes.md
    - '第十九章 工具流工具':
      - '05. workflow工具软件': book/C19_Pipelines-and-Workflows/05_workflow-software.md
    - '第二十章 其他':
      - '02. GI转Accession': book/C20_Others/02_gi-to-accession.md
  - '专项教程':
    - 'Linux入门':
      - '01. Linux 安装示例': tutorial/Linux/01_linux-installation.md
      - '02. Linux 基本命令': tutorial/Linux/02_basic-cml.md
      - '03. Linux 软件管理': tutorial/Linux/03_linux-software.md
      - '04. awk 列处理工具': tutorial/Linux/04_awk.md
      - '05. sed 行处理工具': tutorial/Linux/05_sed.md
      - '06. 其他命令行工具': tutorial/Linux/06_tools.md
      - '07. vim': tutorial/Linux/07_vim.md
    - '常用编程语言':
      - '01. Shell 脚本': tutorial/Programming/01_shell.md
      - '02. Perl 编程': tutorial/Programming/02_perl.md
      - '03. Python 编程': tutorial/Programming/03_python.md
      - '04. Biopython 编程': tutorial/Programming/04_biopython.md
      - '05. R 编程': tutorial/Programming/05_r.md
    - '数据文件格式':
      - '01. fasta': tutorial/Format/01_fasta.md
      - '02. embl': tutorial/Format/02_embl.md
      - '03. fastq': tutorial/Format/05_fastq.md
      - '04. gcg': tutorial/Format/04_gcg.md
      - '05. sam': tutorial/Format/05_sam.md
      - '06. bam': tutorial/Format/06_bam.md
      - '07. bed': tutorial/Format/07_bed.md
      - '08. vcf': tutorial/Format/08_vcf.md
      - '09. gff': tutorial/Format/09_gff.md
      - '10. cram': tutorial/Format/10_cram.md
  - '实验手册':
    - '': protocol.md
    - 'ArticNetwork Covid-19测序': protocol/artic-network-covid19.md
  - '生信笔记':
    - '01 TEST': blog/my-vim-ide.md
    - '02 blast2SRA': blog/blast2sra.md
    - '03 Rmarkdown': blog/tes.md
    - '04 SPAdes': blog/test0316.md
  - '关于我们':
    - '': about.md
use_directory_urls: true

extra_javascript:
  #- https://cdn.rawgit.com/knsv/mermaid/6.0.0/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js
  - assets/js/umlconvert.js

markdown_extensions:
  - codehilite
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.progressbar
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

google_analytics: ['UA-55420348-3', 'auto']

plugins:
  - search
#  - git-authors
#  - git-revision-date
#  - macros
